---
galaxy_info:
  author: kmechlin
  description: Create timeshift snapshots for pre-site.yml rollback safety
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - snapshot
    - timeshift
    - rollback
dependencies: []
